### ISSUE TITLE
Crash with Art of Forging: A Tetra Addon and Epic Fight NBT integration because:  "java.lang.NullPointerException: Cannot invoke "yesman.epicfight.world.capabilities.item.CapabilityItem.setConfigFileAttribute(double, double, int, double, double, int)" because "toReturn" is null"

### ISSUE THREAD

**Issue by InputandOutput** [pitbox46/fightnbtintegration#6] opened 2022-06-19 23:28 UTC
Hello, pitbox46,
I encountered a crash when hovering the cursor/picking up a dreadnought bow item - a feature of Art of Forging: A Tetra Addon - and seemingly Epic Fight + Epic Fight NBT Integration within my custom mod pack. Here is the crash report: 
[crash-2022-06-19_19.08.29-server.txt](https://github.com/pitbox46/fightnbtintegration/files/8936585/crash-2022-06-19_19.08.29-server.txt)
I am wondering as to how to address and fix the issue I am encountering. Please let me know if there is anything I need to do on my end. 

Much Thanks.

**Comment by DanDragonWolf** [comment] 2022-07-04 21:48
I'm having the same issue with the recurve bow from Tetra, so it's not being caused by Art of Forging.

**Comment by pitbox46** [comment] 2022-07-23 21:36
Fixed with [this commit](https://github.com/pitbox46/fightnbtintegration/commit/f8a1e6915dc3e6f8e8a425704b8cdf9111dc138b)

**Closed as completed by pitbox46** 2022-07-23 21:36 UTC
Labels: bug
